name: Docker Build and Push

on:
  push:
    branches: [ main ]
    paths:
      - 'ci_cd/python/Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
      - 'ci_cd/python/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DOCKER_IMAGE: ghcr.io/prasmin/talk-booking:cicd-python3.11-slim
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        run: |
          cd ci_cd/python/
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE
