name: Terraform VPC

on:
  push:
    branches: [main]
    paths:
      - "infrastructure/global/vpc/**"
  pull_request:
    branches: [main]
    paths:
      - "infrastructure/global/vpc/**"

env:
  TF_ROOT: infrastructure/global/vpc

jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ${{ env.TF_ROOT }}
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: ${{ env.TF_ROOT }}
        run: terraform validate

  plan:
    name: Terraform Plan
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ${{ env.TF_ROOT }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ env.TF_ROOT }}
        run: terraform plan -out=tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: ${{ env.TF_ROOT }}/tfplan

  apply:
    name: Terraform Apply
    needs: plan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Download Plan Artifact
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: ${{ env.TF_ROOT }}

      - name: Terraform Apply
        working-directory: ${{ env.TF_ROOT }}
        run: terraform apply -input=false tfplan
